---
- hosts: all
  become: true
  tasks:
    - name: Install apache httpd
      ansible.builtin.yum:
        name: httpd
        state: present
        update_cache: yes
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'