-
  name: this is our third play.
  hosts: web_db_server
  tasks:
      - 
        name: "create a dummy directory on websever1 and dbserver1"
        command: mkdir -p /tmp/ansible_dummy_dir_web_db_server.txt
      -
        name: "create a dummy file on websever1 and dbserver1"
        command: touch /tmp/ansible_dummy_file_web_db_server.txt
