---
- name: User Management Playbook
  hosts: node1
  become: yes  # Ensure the tasks are run with root privileges
  vars:
    domain_or_ip: 10.125.108.19
    users:
      - username: user1
        group: admin
      - username: user2
        group: developers
      - username: user3
        group: support

  tasks:

    - name: Remove users  
      ansible.builtin.user:
        name: "{{ item.username }}"
        state: absent
        remove: yes
      loop: "{{ users }}"
    
    - name: Groups Remove
      ansible.builtin.group:
        name: "{{ item.group }}"
        state: absent
      loop: "{{ users }}"

