---
- name: Install HTTP services on Node1
  hosts: node1
  become: yes

  tasks:
    - name: Install httpd packages
      package:
        name:
        - httpd
        state: present

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes